# Generated by Django 4.1.1 on 2022-09-09 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialCalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[(None, 'Select Subject'), ('Acc', 'Accounting'), ('EW', 'Essay Writing'), ('PSci', 'Political Science'), ('LabR', 'Lab Report'), ('Res', 'Resume')], max_length=50)),
                ('accademic_level', models.CharField(choices=[(None, 'Select your accademic level'), ('HS', 'High School'), ('COL', 'College'), ('UNI', 'University'), ('PG', 'Post Graduate')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InitialCal',
                'verbose_name_plural': 'InitialCals',
            },
        ),
    ]
