# Generated by Django 4.1.1 on 2022-09-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialcalorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
