# Generated by Django 4.1.1 on 2022-09-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreorder', '0002_alter_initialcalorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialcalorder',
            name='pages',
            field=models.IntegerField(default=1),
        ),
    ]
