# Generated by Django 4.1.1 on 2022-09-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreorder', '0004_alter_initialcalorder_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialcalorder',
            options={'get_latest_by': ['created_at'], 'verbose_name': 'InitialCal', 'verbose_name_plural': 'InitialCals'},
        ),
        migrations.AddField(
            model_name='initialcalorder',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='initialcalorder',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
